### ISSUE TITLE
SQLite Install Setup and database creation

### ISSUE THREAD

**Issue by nickGarska** [COSC481W-2024Winter/StormStats#1]
**User Story**
Neilo is collecting their data about their games and wants to be able to have it organized and viewable so they can use it to make future decisions. Having it in a Database will accomplish both of these things as well as allow the data to be easily exportable in a standardized format. Neilo also wants their data to be organized in a way that separates themselves and everyone else by having their own profile.

**Persona**
User of App
**Feature**
Database
**Business Value**
information storage and access

**Tasks**
- [ ] Install SQlite
- [ ] make a user profile
- [ ] make data objects for holding the statistics **(Mar. 11)**
   - [x] a class for a user: name, id, game statistics, etc.
   - [x] a class for an encounter: a game counter, the user id, and other game statistics
   - [x] a list that stores all the encounters
   - [x] a list that stores all the users
- [ ] in SQLite, create a table for users, including their names, ids, game statistics, etc. **(Mar. 13)**
- [ ] in SQLite, create a table for encounters, including a game counter, the user id, and other game statistics, etc.

**Acceptance Criteria**

1. Database exists
2. Database has user Profile
3. Database has way to store all other information
4. The backend Java code can add/edit/remove a user profile in the database
