### ISSUE TITLE
Manual Data Input Via UI interface

### ISSUE THREAD

**Issue by nickGarska** [COSC481W-2024Winter/StormStats#2]
**User Story**
Neilo has just completed a game and he is now viewing the end-of-game score screen. Neilo wants to Collect and save this information and have it automatically combined with any other information that they have collected previously. If Neilo made a mistake such as not inputing a data field or using invalid inputs, such as letters for a numerical statistic the App should not allow him to submit the information until the mistake has been fixed.

**Persona**
User of App
**Feature**
Database Input
**Business Value**
information storage
_Neilo wants to keep the collected data in one place and check them in the future._

**Tasks**

- [x] In the UiController Class make all the functions for the Manual Input Tab
- [x] Connect all functions to their appropriate UI element
- [x] set up Checks for submit button to prevent wrong input
- [x] Provide feedback to user so they know their input was/was not successful
- [x] On successful submission information should be collected and sent to java via functions.
- [x] On successful submission clear any text fields that will not have repeated information to prevent accidental duplicate input on additional data inputs

**Acceptance Criteria**

1. The submit button should check all the text fields for correctness before accepting their input.
2. The submit button should collect the information from the text fields and give it to the java backend.

**Comment by sjiang1** [comment]
Done in c2273325247788204eabfd44eb8f30678f0ac456
