### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2024Winter/StormStats#5]
**User Story**
Neilo wants to use HeroStats but doesn't know anything about Java programming. To use HeroStats, he wants to install HeroStats easily so that he can use HeroStats right away.

**Persona**
Neilo
**Feature**
Provide an installation package with an easy process
**Business Value**
Neilo can use HeroStats right away

**Tasks**
- [ ] Create an installation package for a JavaFX program
- [ ] Include all the libraries in the installation package
- [ ] Include all the resources in the installation package
- [ ] Test the installation on Mac OS
- [ ] Test the installation on Windows OS
- [ ] Publish the installation package on GitHub

**Acceptance Criteria**
1. The user can install HeroStats on their Mac laptop and use HeroStats with data stored locally.
3. The user can install HeroStats on their Windows laptop and use HeroStats with data stored locally.

**Comment by sjiang1** [comment]
Over the Spring break, I tried for an hour to compile the project on MacOS, but I didn't make it work. Decided to avoid Mac for this project.

Today, I found one promising document for deployment:
https://netbeans.apache.org/tutorial/main/kb/docs/java/javase-deploy/

**Comment by sjiang1** [comment]
Export the Java application in Eclipse using "runnable JAR"


![Image](https://github.com/COSC481W-2024Winter/StormStats/assets/2203934/53d52207-b56e-4f30-9ecc-3835a9c5838c)

The Jar was created but nothing happened after clicking the JAR file.

**Comment by sjiang1** [comment]
Figured out a way to run the runnable jar file from command line:
`java -jar C:HeroStats.jar`

**Comment by sjiang1** [comment]
Checked a video: https://www.youtube.com/watch?v=F8ahBtXkQzU for creating an executable jar file.

**Comment by sjiang1** [comment]
Made a folder: `src/resources/` to store the database file under the runnable. The jar is started with exited with error:

![Image](https://github.com/COSC481W-2024Winter/StormStats/assets/2203934/93a4e531-fc40-4ccd-9883-67574dcd9779)
