### ISSUE TITLE
Dump database into java playerlist on startup

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2024Winter/StormStats#8]
**User Story**
When opening the application neilo wants to see previously inputted data, it should be in the app without any user input on app startup.

**Persona**
User of app
**Feature**
Data Viewing
**Business Value**
Data Viewing

**Tasks**

- [x] Write code to load data from the database
- [ ] Figure out how to make the observable list dynamic
- [ ] Put the data into the observable list

**Acceptance Criteria**

- When the database is empty, the application should show no data in the app.
- When the database is not empty, the application should show the games and the encounters.
- The database should be displayed on startup without the user doing anything
